<#
# uMailServer Installer for Windows
# Installs uMailServer as a Windows Service
#

param(
    [string]$ConfigFile = "",
    [string]$DataDir = "C:\ProgramData\umailserver",
    [string]$InstallDir = "C:\Program Files\umailserver",
    [string]$Hostname = "",
    [string]$AdminEmail = "",
    [string]$Domain = "",
    [switch]$NoService,
    [switch]$SkipSetup,
    [switch]$AssumeYes
)

$ErrorActionPreference = "Stop"

# Default paths
$DefaultDataDir = "C:\ProgramData\umailserver"
$DefaultInstallDir = "$env:ProgramFiles\umailserver"
$DefaultConfigDir = "$env:PROGRAMDATA\umailserver"  # Same as data dir on Windows

# Colors
function Write-Info($message) { Write-Host "[INFO] $message" -ForegroundColor Green }
function Write-Warn($message) { Write-Host "[WARN] $message" -ForegroundColor Yellow }
function Write-Err($message) { Write-Host "[ERROR] $message" -ForegroundColor Red }

# Check if running as admin
function Test-Admin {
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

# Create directories
function New-Directories {
    param([string]$DataDir, [string]$InstallDir)

    $dirs = @($DataDir, "$DataDir\data", "$DataDir\log", "$DataDir\run", $InstallDir)

    foreach ($dir in $dirs) {
        if (-not (Test-Path $dir)) {
            Write-Info "Creating directory: $dir"
            New-Item -ItemType Directory -Path $dir -Force | Out-Null
        } else {
            Write-Info "Directory exists: $dir"
        }
    }
}

# Generate random JWT secret
function New-Secret {
    $bytes = New-Object byte[] 32
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($bytes)
    return [Convert]::ToBase64String($bytes) | Select-Object -First 32
}

# Create config file
function New-Config {
    param(
        [string]$ConfigPath,
        [string]$Hostname,
        [string]$AdminEmail,
        [string]$Domain,
        [string]$DataDir
    )

    $jwtSecret = New-Secret

    $config = @"
# uMailServer Configuration
# Generated by install.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

server:
  hostname: $Hostname
  data_dir: $DataDir\data

tls:
  cert_file: ""
  key_file: ""
  min_version: "1.2"
  acme:
    enabled: true
    email: $AdminEmail
    provider: letsencrypt
    challenge: http-01

smtp:
  inbound:
    enabled: true
    port: 25
    bind: "0.0.0.0"
    max_message_size: 50MB
    max_recipients: 100
    max_connections: 10000
  submission:
    enabled: true
    port: 587
    bind: "0.0.0.0"
    require_auth: true
    require_tls: true
  submission_tls:
    enabled: true
    port: 465
    bind: "0.0.0.0"
    require_auth: true

imap:
  enabled: true
  port: 993
  bind: "0.0.0.0"
  starttls_port: 143

pop3:
  enabled: false
  port: 995
  bind: "0.0.0.0"

http:
  enabled: true
  port: 443
  http_port: 80
  bind: "0.0.0.0"
  cors_origins: []

admin:
  enabled: true
  bind: "127.0.0.1"
  port: 8443

security:
  max_login_attempts: 5
  lockout_duration: 15m
  jwt_secret: "$jwtSecret"
  rate_limit:
    smtp_per_minute: 30
    smtp_per_hour: 500
    imap_connections: 50
    http_requests_per_minute: 120

spam:
  enabled: true
  reject_threshold: 9.0
  junk_threshold: 3.0
  quarantine_threshold: 6.0
  bayesian:
    enabled: true
    auto_train: true
  greylisting:
    enabled: true
    delay: 5m
  rbl_servers:
    - zen.spamhaus.org
    - b.barracudacentral.org

av:
  enabled: false
  addr: "127.0.0.1:3310"

mcp:
  enabled: true
  port: 3000
  bind: "127.0.0.1"

logging:
  level: info
  format: json
  output: stdout

metrics:
  enabled: true
  port: 8080
  bind: "127.0.0.1"

database:
  path: $DataDir\data\umailserver.db

storage:
  sync: true

domains:
  - name: $Domain
    max_accounts: 100
    max_mailbox_size: 5GB
"@

    $config | Out-File -FilePath $ConfigPath -Encoding UTF8 -Force
    Write-Info "Configuration created: $ConfigPath"
}

# Create Windows service wrapper
function New-WinService {
    param([string]$InstallDir, [string]$ConfigPath, [string]$DataDir)

    $serviceWrapper = @"
// Windows Service wrapper for uMailServer
// Build: go build -o umailserver-service.exe ./cmd/service
package main

import (
    "os"
    "os/exec"
    "syscall"
    "time"

    "golang.org/x/sys/windows/svc"
    "golang.org/x/sys/windows/svc/debug"
    "golang.org/x/sys/windows/svc/eventlog"
)

func main() {
    const svcName = "umailserver"

    var err error
    var isInteractive bool

    isInteractive, err = svc.IsWindowsService()
    if err != nil {
        eventlog.Error(1, "Failed to determine service status: %v", err)
        os.Exit(1)
    }

    if isInteractive {
        debug.Run(svcName, &umailserverService{})
    } else {
        svc.Run(svcName, &umailserverService{})
    }
}

type umailserverService struct{}

func (m *umailserverService) Execute(args []string, r <-chan svc.ChangeRequest, changes chan<- svc.Status) (ssec bool, errno uint32) {
    const cmdsAccepted = svc.AcceptStop | svc.AcceptShutdown

    go func() {
        exe := "` + "$InstallDir" + `\umailserver.exe"
        cmd := exec.Command(exe, "serve", "--config", "` + "$ConfigPath" + `")
        cmd.Stdout = os.Stdout
        cmd.Stderr = os.Stderr
        cmd.SysProcAttr = &syscall.SysProcAttr{
            CreationFlags: syscall.CREATE_NEW_PROCESS_GROUP,
        }
        err := cmd.Start()
        if err != nil {
            eventlog.Error(1, "Failed to start umailserver: %v", err)
            return
        }

        changes <- svc.Status{State: svc.Running}

        err = cmd.Wait()
        if err != nil {
            eventlog.Error(1, "umailserver exited with error: %v", err)
        }
    }()

    for {
        c := <-r
        switch c.Cmd {
        case svc.Interrogate:
            changes <- c.CurrentStatus
        case svc.Stop, svc.Shutdown:
            changes <- svc.Status{State: svc.StopPending}
            time.Sleep(5 * time.Second)
            return
        default:
        }
    }
}
"@

    Write-Warn "Windows service requires NSSM or similar service manager."
    Write-Info "Alternative: Run as console app with: umailserver.exe serve --config $ConfigPath"
}

# Interactive setup
function Invoke-Setup {
    param([string]$DataDir, [string]$InstallDir)

    Write-Info "Starting interactive setup..."
    Write-Host ""

    # Hostname
    if ([string]::IsNullOrEmpty($Hostname)) {
        Write-Host "=== uMailServer Setup ===" -ForegroundColor Cyan
        Write-Host ""
        do {
            $hostnameInput = Read-Host "Server hostname [mail.example.com]"
            if ([string]::IsNullOrEmpty($hostnameInput)) { $script:Hostname = "mail.example.com" }
            else { $script:Hostname = $hostnameInput }
        } while ([string]::IsNullOrEmpty($script:Hostname))
    }

    # Admin email
    if ([string]::IsNullOrEmpty($AdminEmail)) {
        $defaultEmail = "admin@" + $script:Hostname.Split('.')[1..($script:Hostname.Split('.').Length-1)] -join '.'
        do {
            $emailInput = Read-Host "Admin email [$defaultEmail]"
            if ([string]::IsNullOrEmpty($emailInput)) { $script:AdminEmail = $defaultEmail }
            else { $script:AdminEmail = $emailInput }
        } while ([string]::IsNullOrEmpty($script:AdminEmail))
    }

    # Domain
    if ([string]::IsNullOrEmpty($Domain)) {
        $defaultDomain = $script:Hostname.Split('.')[1..($script:Hostname.Split('.').Length-1)] -join '.'
        do {
            $domainInput = Read-Host "Primary email domain [$defaultDomain]"
            if ([string]::IsNullOrEmpty($domainInput)) { $script:Domain = $defaultDomain }
            else { $script:Domain = $domainInput }
        } while ([string]::IsNullOrEmpty($script:Domain))
    }

    $configPath = "$InstallDir\umailserver.yaml"
    New-Config -ConfigPath $configPath -Hostname $script:Hostname -AdminEmail $script:AdminEmail -Domain $script:Domain -DataDir $DataDir

    Write-Host ""
    Write-Info "Setup complete!"
    Write-Host ""
    Write-Host "Configuration:" -ForegroundColor Cyan
    Write-Host "  Config: $configPath"
    Write-Host "  Data: $DataDir"
}

# Main installation
function Install-uMailServer {
    Write-Host ""
    Write-Info "uMailServer Installer for Windows"
    Write-Host ""

    if (-not (Test-Admin)) {
        Write-Warn "Running as non-admin. Some operations may fail."
        if (-not $AssumeYes) {
            $confirm = Read-Host "Continue anyway? [y/N]"
            if ($confirm -ne "y" -and $confirm -ne "Y") { exit 1 }
        }
    }

    # Create directories
    New-Directories -DataDir $DataDir -InstallDir $InstallDir

    # Copy binary if exists in current directory
    $localBinary = ".\umailserver.exe"
    if (Test-Path $localBinary) {
        Write-Info "Copying binary from current directory..."
        Copy-Item $localBinary "$InstallDir\umailserver.exe" -Force
    } else {
        Write-Info "Binary not found in current directory."
        Write-Info "Please copy umailserver.exe to $InstallDir or run from build directory."
    }

    # Set permissions
    if (Test-Admin) {
        $acl = Get-Acl $DataDir
        $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
            "NT SERVICE\TrustedInstaller", "FullControl",
            "ContainerInherit,ObjectInherit", "None", "Allow"
        )
        # Simplified - just ensure basic permissions
        icacls $DataDir /inheritance:r 2>$null | Out-Null
        icacls $DataDir /grant:r "SYSTEM:(OI)(CI)F" 2>$null | Out-Null
    }

    # Setup
    if (-not $SkipSetup) {
        if ([string]::IsNullOrEmpty($ConfigFile) -or -not (Test-Path $ConfigFile)) {
            Invoke-Setup -DataDir $DataDir -InstallDir $InstallDir
        } else {
            $destConfig = "$InstallDir\umailserver.yaml"
            Copy-Item $ConfigFile $destConfig -Force
            Write-Info "Configuration installed: $destConfig"
        }
    }

    # Create service helper
    New-WinService -InstallDir $InstallDir -ConfigPath "$InstallDir\umailserver.yaml" -DataDir $DataDir

    Write-Host ""
    Write-Info "Installation complete!"
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor Cyan
    Write-Host "  1. Edit config: $InstallDir\umailserver.yaml"
    Write-Host "  2. Install service: nssm install umailserver `"$InstallDir\umailserver.exe`" `"serve --config $InstallDir\umailserver.yaml`""
    Write-Host "  3. Start service: nssm start umailserver"
    Write-Host "  4. Or run directly: $InstallDir\umailserver.exe serve --config $InstallDir\umailserver.yaml"
    Write-Host ""
    Write-Host "Ports:" -ForegroundColor Cyan
    Write-Host "  SMTP:     25, 587, 465"
    Write-Host "  IMAP:     143, 993"
    Write-Host "  POP3:     995"
    Write-Host "  HTTP:     443 (Webmail + Admin)"
    Write-Host "  Admin:    8443 (localhost only)"
    Write-Host "  Metrics:  8080"
    Write-Host "  MCP:      3000"
    Write-Host ""
}

Install-uMailServer
