package main

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/umailserver/umailserver/internal/config"
	"github.com/umailserver/umailserver/internal/db"
	"github.com/umailserver/umailserver/internal/server"
	"golang.org/x/crypto/bcrypt"
)

var (
	Version   = "dev"
	BuildDate = "unknown"
	GitCommit = "unknown"
)

func main() {
	if len(os.Args) < 2 {
		printUsage()
		os.Exit(1)
	}

	switch os.Args[1] {
	case "serve":
		cmdServe(os.Args[2:])
	case "quickstart":
		cmdQuickstart(os.Args[2:])
	case "domain":
		cmdDomain(os.Args[2:])
	case "account":
		cmdAccount(os.Args[2:])
	case "queue":
		cmdQueue(os.Args[2:])
	case "check":
		cmdCheck(os.Args[2:])
	case "test":
		cmdTest(os.Args[2:])
	case "backup":
		cmdBackup(os.Args[2:])
	case "restore":
		cmdRestore(os.Args[2:])
	case "migrate":
		cmdMigrate(os.Args[2:])
	case "version":
		fmt.Printf("uMailServer %s (%s) built %s\n", Version, GitCommit, BuildDate)
	default:
		fmt.Fprintf(os.Stderr, "unknown command: %s\n", os.Args[1])
		printUsage()
		os.Exit(1)
	}
}

func printUsage() {
	fmt.Println(`uMailServer - One binary. Complete email.

Usage: umailserver <command> [flags]

Commands:
  serve        Start the mail server
  quickstart   Generate config and create first account
  domain       Domain management (add, list, dns)
  account      Account management (add, password, list, delete)
  queue        Queue management (list, retry, flush, drop)
  check        Diagnostics (dns, tls, deliverability)
  test         Test utilities (send)
  backup       Create backup
  restore      Restore from backup
  migrate      Import from other mail servers
  version      Show version

Examples:
  umailserver quickstart you@example.com
  umailserver serve --config /etc/umailserver.yaml
  umailserver domain add example.com
  umailserver account add john@example.com
  umailserver check dns example.com`)
}

func cmdServe(args []string) {
	var configPath string
	var dataDir string

	fs := flag.NewFlagSet("serve", flag.ExitOnError)
	fs.StringVar(&configPath, "config", "", "Path to config file")
	fs.StringVar(&dataDir, "data-dir", "", "Override data directory")
	fs.Parse(args)

	// Load configuration
	cfg, err := config.Load(configPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to load config: %v\n", err)
		os.Exit(1)
	}

	// Override data directory if specified
	if dataDir != "" {
		cfg.Server.DataDir = dataDir
	}

	// Create server
	srv, err := server.New(cfg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create server: %v\n", err)
		os.Exit(1)
	}

	// Start server
	if err := srv.Start(); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to start server: %v\n", err)
		os.Exit(1)
	}

	// Wait for shutdown signal
	if err := srv.Wait(); err != nil {
		fmt.Fprintf(os.Stderr, "Server error: %v\n", err)
		os.Exit(1)
	}
}

func cmdQuickstart(args []string) {
	if len(args) < 1 {
		fmt.Println("Usage: umailserver quickstart <email>")
		os.Exit(1)
	}

	email := args[0]
	parts := strings.Split(email, "@")
	if len(parts) != 2 {
		fmt.Fprintf(os.Stderr, "Invalid email format: %s\n", email)
		os.Exit(1)
	}
	domain := parts[1]

	dataDir := "./data"
	configPath := "./umailserver.yaml"

	// Check if config already exists
	if _, err := os.Stat(configPath); err == nil {
		fmt.Printf("Config file already exists: %s\n", configPath)
		fmt.Print("Overwrite? (y/N): ")
		var response string
		fmt.Scanln(&response)
		if response != "y" && response != "Y" {
			fmt.Println("Aborted.")
			os.Exit(0)
		}
	}

	// Generate config
	fmt.Println("=== uMailServer Quickstart ===")
	fmt.Printf("Setting up for: %s\n\n", email)

	// Generate DKIM key
	dkimDir := filepath.Join(dataDir, "dkim")
	os.MkdirAll(dkimDir, 0755)
	dkimKeyPath := filepath.Join(dkimDir, domain+".private.pem")

	fmt.Println("Generating DKIM key pair...")
	if err := generateDKIMKey(dkimKeyPath); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to generate DKIM key: %v\n", err)
		os.Exit(1)
	}

	// Read public key for DNS
	publicKey, err := os.ReadFile(dkimKeyPath + ".pub")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to read DKIM public key: %v\n", err)
		os.Exit(1)
	}

	// Write config
	config := fmt.Sprintf(`# uMailServer Configuration
# Generated by quickstart for %s

server:
  hostname: mail.%s
  data_dir: %s

tls:
  acme:
    enabled: true
    email: %s
    provider: letsencrypt

smtp:
  inbound:
    port: 25
    max_message_size: 52428800  # 50MB
    max_recipients: 100
  submission:
    port: 587
    require_auth: true
    require_tls: true
  submission_tls:
    port: 465

imap:
  port: 993

http:
  port: 443
  http_port: 80

admin:
  port: 8443
  bind: 127.0.0.1

spam:
  reject_threshold: 9.0
  junk_threshold: 3.0
  greylisting:
    enabled: true
    delay: 5m

dkim:
  enabled: true
  selector: default
  domain: %s
  key_file: %s

domains:
  - name: %s
    max_accounts: 100
    max_mailbox_size: 5368709120  # 5GB
`, email, domain, dataDir, email, domain, dkimKeyPath, domain)

	if err := os.WriteFile(configPath, []byte(config), 0600); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write config: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✓ Config written to: %s\n", configPath)
	fmt.Printf("✓ Data directory: %s\n", dataDir)

	// Initialize database
	fmt.Println("\nInitializing database...")
	dbPath := filepath.Join(dataDir, "umailserver.db")
	if err := os.MkdirAll(dataDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create data directory: %v\n", err)
		os.Exit(1)
	}

	database, err := db.Open(dbPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to open database: %v\n", err)
		os.Exit(1)
	}
	defer database.Close()

	// Create domain
	if err := database.CreateDomain(&db.DomainData{
		Name:        domain,
		MaxAccounts: 100,
		IsActive:    true,
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	}); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create domain: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("✓ Domain created: %s\n", domain)

	// Create admin account with password prompt
	fmt.Print("\nEnter admin password: ")
	password := readPassword()

	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to hash password: %v\n", err)
		os.Exit(1)
	}

	if err := database.CreateAccount(&db.AccountData{
		Email:        email,
		LocalPart:    parts[0],
		Domain:       domain,
		PasswordHash: string(hash),
		IsAdmin:      true,
		IsActive:     true,
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	}); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create account: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("✓ Admin account created: %s\n", email)

	// Print DNS records
	fmt.Println("\n=== Required DNS Records ===")
	fmt.Println("\n# MX Record:")
	fmt.Printf("%s.    IN    MX    10    mail.%s.\n\n", domain, domain)

	fmt.Println("# A Records:")
	fmt.Printf("mail.%s.    IN    A    <YOUR_SERVER_IP>\n\n", domain)

	fmt.Println("# SPF Record:")
	fmt.Printf("%s.    IN    TXT    \"v=spf1 mx ~all\"\n\n", domain)

	fmt.Println("# DKIM Record (default._domainkey):")
	dkimRecord := fmt.Sprintf("v=DKIM1; k=rsa; p=%s", strings.TrimSpace(string(publicKey)))
	fmt.Printf("default._domainkey.%s.    IN    TXT    \"%s\"\n\n", domain, dkimRecord)

	fmt.Println("# DMARC Record:")
	fmt.Printf("_dmarc.%s.    IN    TXT    \"v=DMARC1; p=quarantine; rua=mailto:dmarc@%s\"\n\n", domain, domain)

	fmt.Println("=== Next Steps ===")
	fmt.Println("1. Update DNS records above with your actual server IP")
	fmt.Println("2. Start the server: umailserver serve -config umailserver.yaml")
	fmt.Println("3. Access webmail at: https://mail.yourdomain.com")
	fmt.Println("4. Access admin panel at: https://127.0.0.1:8443")
}

func generateDKIMKey(keyPath string) error {
	// Generate RSA key
	privateKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return err
	}

	// Write private key
	privateKeyPEM := &pem.Block{
		Type:  "RSA PRIVATE KEY",
		Bytes: x509.MarshalPKCS1PrivateKey(privateKey),
	}

	privateKeyFile, err := os.Create(keyPath)
	if err != nil {
		return err
	}
	defer privateKeyFile.Close()

	if err := pem.Encode(privateKeyFile, privateKeyPEM); err != nil {
		return err
	}

	// Write public key
	publicKeyBytes, err := x509.MarshalPKIXPublicKey(&privateKey.PublicKey)
	if err != nil {
		return err
	}

	publicKeyPEM := &pem.Block{
		Type:  "PUBLIC KEY",
		Bytes: publicKeyBytes,
	}

	publicKeyFile, err := os.Create(keyPath + ".pub")
	if err != nil {
		return err
	}
	defer publicKeyFile.Close()

	if err := pem.Encode(publicKeyFile, publicKeyPEM); err != nil {
		return err
	}

	return nil
}

func readPassword() string {
	// Simple password reader (cross-platform)
	var password string
	fmt.Scanln(&password)
	return password
}

func cmdDomain(args []string) {
	if len(args) < 1 {
		fmt.Println("Usage: umailserver domain <subcommand>")
		fmt.Println("Subcommands: add, list, dns, delete")
		os.Exit(1)
	}

	subcmd := args[0]

	// Load database
	dataDir := "./data"
	dbPath := filepath.Join(dataDir, "umailserver.db")
	database, err := db.Open(dbPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to open database: %v\n", err)
		os.Exit(1)
	}
	defer database.Close()

	switch subcmd {
	case "add":
		if len(args) < 2 {
			fmt.Println("Usage: umailserver domain add <domain>")
			os.Exit(1)
		}
		domainName := args[1]
		if err := database.CreateDomain(&db.DomainData{
			Name:        domainName,
			MaxAccounts: 100,
			IsActive:    true,
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		}); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to create domain: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("✓ Domain created: %s\n", domainName)

	case "list":
		domains, err := database.ListDomains()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to list domains: %v\n", err)
			os.Exit(1)
		}
		if len(domains) == 0 {
			fmt.Println("No domains found.")
			return
		}
		fmt.Println("Domains:")
		fmt.Println("--------")
		for _, d := range domains {
			status := "active"
			if !d.IsActive {
				status = "inactive"
			}
			fmt.Printf("%-30s %s (%d/%d accounts)\n", d.Name, status, 0, d.MaxAccounts)
		}

	case "dns":
		if len(args) < 2 {
			fmt.Println("Usage: umailserver domain dns <domain>")
			os.Exit(1)
		}
		domainName := args[1]
		domain, err := database.GetDomain(domainName)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Domain not found: %s\n", domainName)
			os.Exit(1)
		}

		fmt.Printf("\n=== DNS Records for %s ===\n\n", domain.Name)

		fmt.Println("# MX Record:")
		fmt.Printf("%s.    IN    MX    10    mail.%s.\n\n", domain.Name, domain.Name)

		fmt.Println("# A Record:")
		fmt.Printf("mail.%s.    IN    A    <YOUR_SERVER_IP>\n\n", domain.Name)

		fmt.Println("# SPF Record:")
		fmt.Printf("%s.    IN    TXT    \"v=spf1 mx ~all\"\n\n", domain.Name)

		fmt.Println("# DKIM Record (default._domainkey):")
		fmt.Printf("default._domainkey.%s.    IN    TXT    \"v=DKIM1; k=rsa; p=<YOUR_DKIM_KEY>\"\n\n", domain.Name)

		fmt.Println("# DMARC Record:")
		fmt.Printf("_dmarc.%s.    IN    TXT    \"v=DMARC1; p=quarantine; rua=mailto:dmarc@%s\"\n\n", domain.Name, domain.Name)

		fmt.Println("Replace <YOUR_SERVER_IP> and <YOUR_DKIM_KEY> with actual values.")

	case "delete":
		if len(args) < 2 {
			fmt.Println("Usage: umailserver domain delete <domain>")
			os.Exit(1)
		}
		domainName := args[1]

		// Confirm deletion
		fmt.Printf("Are you sure you want to delete domain %s? This will delete all accounts! (y/N): ", domainName)
		var response string
		fmt.Scanln(&response)
		if response != "y" && response != "Y" {
			fmt.Println("Aborted.")
			os.Exit(0)
		}

		if err := database.DeleteDomain(domainName); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to delete domain: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("✓ Domain deleted: %s\n", domainName)

	default:
		fmt.Fprintf(os.Stderr, "Unknown domain subcommand: %s\n", subcmd)
		os.Exit(1)
	}
}

func cmdAccount(args []string) {
	if len(args) < 1 {
		fmt.Println("Usage: umailserver account <subcommand>")
		fmt.Println("Subcommands: add, password, list, delete")
		os.Exit(1)
	}

	subcmd := args[0]

	// Load database
	dataDir := "./data"
	dbPath := filepath.Join(dataDir, "umailserver.db")
	database, err := db.Open(dbPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to open database: %v\n", err)
		os.Exit(1)
	}
	defer database.Close()

	switch subcmd {
	case "add":
		if len(args) < 2 {
			fmt.Println("Usage: umailserver account add <email>")
			os.Exit(1)
		}
		email := args[1]
		parts := strings.Split(email, "@")
		if len(parts) != 2 {
			fmt.Fprintf(os.Stderr, "Invalid email format: %s\n", email)
			os.Exit(1)
		}

		// Check if domain exists
		_, err := database.GetDomain(parts[1])
		if err != nil {
			fmt.Fprintf(os.Stderr, "Domain not found: %s (create it first with 'umailserver domain add')\n", parts[1])
			os.Exit(1)
		}

		// Get password
		fmt.Print("Enter password: ")
		password := readPassword()
		if len(password) < 8 {
			fmt.Fprintf(os.Stderr, "Password must be at least 8 characters\n")
			os.Exit(1)
		}

		hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to hash password: %v\n", err)
			os.Exit(1)
		}

		if err := database.CreateAccount(&db.AccountData{
			Email:        email,
			LocalPart:    parts[0],
			Domain:       parts[1],
			PasswordHash: string(hash),
			IsAdmin:      false,
			IsActive:     true,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		}); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to create account: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("✓ Account created: %s\n", email)

	case "list":
		var domain string
		if len(args) >= 2 {
			domain = args[1]
		}

		var accounts []*db.AccountData
		var err error

		if domain != "" {
			accounts, err = database.ListAccountsByDomain(domain)
		} else {
			// List all accounts
			domains, err := database.ListDomains()
			if err != nil {
				fmt.Fprintf(os.Stderr, "Failed to list domains: %v\n", err)
				os.Exit(1)
			}
			for _, d := range domains {
				domainAccounts, _ := database.ListAccountsByDomain(d.Name)
				accounts = append(accounts, domainAccounts...)
			}
		}

		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to list accounts: %v\n", err)
			os.Exit(1)
		}

		if len(accounts) == 0 {
			fmt.Println("No accounts found.")
			return
		}

		fmt.Println("Accounts:")
		fmt.Println("---------")
		for _, a := range accounts {
			status := "active"
			if !a.IsActive {
				status = "inactive"
			}
			admin := ""
			if a.IsAdmin {
				admin = "[admin]"
			}
			fmt.Printf("%-40s %s %s\n", a.Email, status, admin)
		}

	case "password":
		if len(args) < 2 {
			fmt.Println("Usage: umailserver account password <email>")
			os.Exit(1)
		}
		email := args[1]
		parts := strings.Split(email, "@")
		if len(parts) != 2 {
			fmt.Fprintf(os.Stderr, "Invalid email format: %s\n", email)
			os.Exit(1)
		}

		account, err := database.GetAccount(parts[1], parts[0])
		if err != nil {
			fmt.Fprintf(os.Stderr, "Account not found: %s\n", email)
			os.Exit(1)
		}

		fmt.Print("Enter new password: ")
		password := readPassword()
		if len(password) < 8 {
			fmt.Fprintf(os.Stderr, "Password must be at least 8 characters\n")
			os.Exit(1)
		}

		hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to hash password: %v\n", err)
			os.Exit(1)
		}

		account.PasswordHash = string(hash)
		account.UpdatedAt = time.Now()

		if err := database.UpdateAccount(account); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to update password: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("✓ Password updated for: %s\n", email)

	case "delete":
		if len(args) < 2 {
			fmt.Println("Usage: umailserver account delete <email>")
			os.Exit(1)
		}
		email := args[1]
		parts := strings.Split(email, "@")
		if len(parts) != 2 {
			fmt.Fprintf(os.Stderr, "Invalid email format: %s\n", email)
			os.Exit(1)
		}

		// Confirm deletion
		fmt.Printf("Are you sure you want to delete account %s? (y/N): ", email)
		var response string
		fmt.Scanln(&response)
		if response != "y" && response != "Y" {
			fmt.Println("Aborted.")
			os.Exit(0)
		}

		if err := database.DeleteAccount(parts[1], parts[0]); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to delete account: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("✓ Account deleted: %s\n", email)

	default:
		fmt.Fprintf(os.Stderr, "Unknown account subcommand: %s\n", subcmd)
		os.Exit(1)
	}
}

func cmdQueue(args []string) {
	if len(args) < 1 {
		fmt.Println("Usage: umailserver queue <subcommand>")
		fmt.Println("Subcommands: list, retry, flush, drop")
		os.Exit(1)
	}

	subcmd := args[0]
	fmt.Printf("Queue command: %s\n", subcmd)

	switch subcmd {
	case "list":
		fmt.Println("Listing queue entries...")
	case "retry":
		if len(args) < 2 {
			fmt.Println("Usage: umailserver queue retry <id>")
			os.Exit(1)
		}
		fmt.Printf("Retrying queue entry: %s\n", args[1])
	case "flush":
		fmt.Println("Flushing queue...")
	case "drop":
		if len(args) < 2 {
			fmt.Println("Usage: umailserver queue drop <id>")
			os.Exit(1)
		}
		fmt.Printf("Dropping queue entry: %s\n", args[1])
	default:
		fmt.Fprintf(os.Stderr, "Unknown queue subcommand: %s\n", subcmd)
		os.Exit(1)
	}
}

func cmdCheck(args []string) {
	if len(args) < 1 {
		fmt.Println("Usage: umailserver check <type>")
		fmt.Println("Types: dns, tls, deliverability")
		os.Exit(1)
	}

	checkType := args[0]
	fmt.Printf("Check command: %s\n", checkType)

	switch checkType {
	case "dns":
		if len(args) < 2 {
			fmt.Println("Usage: umailserver check dns <domain>")
			os.Exit(1)
		}
		fmt.Printf("Checking DNS for: %s\n", args[1])
	case "tls":
		if len(args) < 2 {
			fmt.Println("Usage: umailserver check tls <domain>")
			os.Exit(1)
		}
		fmt.Printf("Checking TLS for: %s\n", args[1])
	case "deliverability":
		if len(args) < 2 {
			fmt.Println("Usage: umailserver check deliverability <domain>")
			os.Exit(1)
		}
		fmt.Printf("Checking deliverability for: %s\n", args[1])
	default:
		fmt.Fprintf(os.Stderr, "Unknown check type: %s\n", checkType)
		os.Exit(1)
	}
}

func cmdTest(args []string) {
	if len(args) < 1 {
		fmt.Println("Usage: umailserver test <type>")
		fmt.Println("Types: send")
		os.Exit(1)
	}

	testType := args[0]
	fmt.Printf("Test command: %s\n", testType)

	switch testType {
	case "send":
		if len(args) < 4 {
			fmt.Println("Usage: umailserver test send <from> <to> <subject>")
			os.Exit(1)
		}
		fmt.Printf("Sending test email from %s to %s\n", args[1], args[2])
	default:
		fmt.Fprintf(os.Stderr, "Unknown test type: %s\n", testType)
		os.Exit(1)
	}
}

func cmdBackup(args []string) {
	if len(args) < 1 {
		fmt.Println("Usage: umailserver backup <path>")
		os.Exit(1)
	}
	fmt.Printf("Backup to: %s\n", args[0])
}

func cmdRestore(args []string) {
	if len(args) < 1 {
		fmt.Println("Usage: umailserver restore <path>")
		os.Exit(1)
	}
	fmt.Printf("Restore from: %s\n", args[0])
}

func cmdMigrate(args []string) {
	if len(args) < 2 {
		fmt.Println("Usage: umailserver migrate --source <type>")
		fmt.Println("Source types: postfix, dovecot, maildir")
		os.Exit(1)
	}
	fmt.Println("Migrate command (not yet implemented)")
}
