package store

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"sync/atomic"
	"time"
)

// MaildirStore implements Maildir++ format storage
type MaildirStore struct {
	baseDir string
}

// MessageInfo holds metadata about a message
type MessageInfo struct {
	Filename string
	Size     int64
	ModTime  time.Time
	Flags    string
	UID      uint32
}

// flagSeparator returns the platform-compatible flag separator
// Maildir uses ":2," but Windows doesn't allow ":" in filenames
func flagSeparator() string {
	if runtime.GOOS == "windows" {
		return "!2,"
	}
	return ":2,"
}

// splitFlags splits a filename into base name and flags
func splitFlags(filename string) (baseName, flags string) {
	sep := flagSeparator()
	if idx := strings.Index(filename, sep); idx != -1 {
		return filename[:idx], filename[idx+len(sep):]
	}
	// Try standard Maildir format as fallback
	if idx := strings.Index(filename, ":2,"); idx != -1 {
		return filename[:idx], filename[idx+3:]
	}
	return filename, ""
}

// joinFlags joins base name with flags
func joinFlags(baseName, flags string) string {
	flags = canonicalFlags(flags)
	if flags == "" {
		return baseName
	}
	return baseName + flagSeparator() + flags
}

// canonicalFlags returns flags in ASCII order without duplicates, as the
// Maildir spec requires for the info field after ":2," (F5725).
func canonicalFlags(flags string) string {
	b := []byte(flags)
	sort.Slice(b, func(i, j int) bool { return b[i] < b[j] })
	out := b[:0]
	for i, c := range b {
		if i == 0 || c != b[i-1] {
			out = append(out, c)
		}
	}
	return string(out)
}

// NewMaildirStore creates a new Maildir store
func NewMaildirStore(baseDir string) *MaildirStore {
	return &MaildirStore{
		baseDir: baseDir,
	}
}

// validatePathParts checks that domain and user don't contain path traversal sequences.
func validatePathParts(domain, user string) error {
	for _, s := range []string{domain, user} {
		// F5726: "." collapses a path level (domain) or aliases a parent dir.
		if s == "" || s == "." || s == ".." || strings.ContainsAny(s, "/\\") {
			return fmt.Errorf("invalid path component: %q", s)
		}
	}
	return nil
}

// validateFilename checks that a filename doesn't contain path traversal sequences.
// Maildir filenames are generated by generateUniqueName() and have format:
// {timestamp}.{pid}.{hostname}:2,{flags}
// However, when accepting filenames from external sources, we validate to prevent attacks.
func validateFilename(filename string) error {
	if filename == "" || filename == ".." || strings.ContainsAny(filename, "/\\") {
		return fmt.Errorf("invalid filename: %q", filename)
	}
	return nil
}

// userMaildirPath returns the path to a user's Maildir.
// It validates domain and user to prevent path traversal.
func (s *MaildirStore) userMaildirPath(domain, user string) (string, error) {
	if err := validatePathParts(domain, user); err != nil {
		return "", err
	}
	return filepath.Join(s.baseDir, "domains", domain, "users", user, "Maildir"), nil
}

// folderPath returns the path to a specific folder within a user's Maildir
func (s *MaildirStore) folderPath(domain, user, folder string) string {
	maildir, err := s.userMaildirPath(domain, user)
	if err != nil {
		return ""
	}
	if folder == "" || folder == "INBOX" {
		return maildir
	}
	// Maildir++ folder naming: .Folder.Subfolder
	if strings.ContainsAny(folder, "./\\") {
		return ""
	}
	return filepath.Join(maildir, "."+folder)
}

// ensureFolder creates the Maildir structure for a folder if it doesn't exist
func (s *MaildirStore) ensureFolder(domain, user, folder string) error {
	basePath := s.folderPath(domain, user, folder)
	if basePath == "" {
		return fmt.Errorf("invalid mailbox path")
	}

	subdirs := []string{"tmp", "new", "cur"}
	for _, subdir := range subdirs {
		path := filepath.Join(basePath, subdir)
		if err := os.MkdirAll(path, 0o750); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", path, err)
		}
	}

	return nil
}

// maildirNameSeq is the per-process delivery counter that makes maildir
// filenames unique and lexicographically monotonic.
var maildirNameSeq atomic.Uint64

// formatMaildirName renders a maildir unique filename from its components.
// It is a pure function so the ordering and uniqueness properties of the
// format can be tested with adversarial inputs. Fixed-width fields keep
// lexicographic order identical to delivery order across digit-width
// transitions (micros is zero-padded to 6, the per-process counter to 20).
func formatMaildirName(timestamp int64, micros int64, pid int, seq uint64, hostname string) string {
	return fmt.Sprintf("%d.M%06dP%dQ%020d.%s", timestamp, micros, pid, seq, hostname)
}

// generateUniqueName generates a unique Maildir filename. The format is
// owned by formatMaildirName: "%d.M%06dP%dQ%020d.%s" — zero-padded micros and
// per-process counter keep lexicographic filename order equal to delivery
// order, and the counter makes same-process collisions impossible.
func (s *MaildirStore) generateUniqueName() string {
	timestamp := time.Now().Unix()
	pid := os.Getpid()
	hostname, _ := os.Hostname()
	if hostname == "" {
		hostname = "localhost"
	}
	hostname = sanitizeHostname(hostname)
	// The per-process counter guarantees uniqueness (no two deliveries in
	// this process can share a name, so rename cannot overwrite a message),
	// and the fixed-width zero-padded fields keep lexicographic filename
	// order identical to delivery order — maildir listings are
	// filename-sorted and message order must match delivery order.
	seq := maildirNameSeq.Add(1)
	micros := time.Now().UnixMicro() % 1000000
	return formatMaildirName(timestamp, micros, pid, seq, hostname)
}

// sanitizeHostname replaces path separators and the flag delimiter in the
// unique-name host part with "_" so a hostname can never introduce a path
// component or flag split (F5953). (The spec's backslash escapes would be
// rejected by validateFilename.)
func sanitizeHostname(h string) string {
	return strings.NewReplacer("/", "_", "\\", "_", ":", "_").Replace(h)
}

// Deliver stores a message in the specified folder
// Uses atomic delivery: write to tmp/, then rename to new/
func (s *MaildirStore) Deliver(domain, user, folder string, msg []byte) (string, error) {
	if err := s.ensureFolder(domain, user, folder); err != nil {
		return "", err
	}

	basePath := s.folderPath(domain, user, folder)
	uniqueName := s.generateUniqueName()

	// Write to tmp directory first
	tmpPath := filepath.Join(basePath, "tmp", uniqueName)
	newPath := filepath.Join(basePath, "new", uniqueName)

	// Write file
	if err := os.WriteFile(tmpPath, msg, 0o600); err != nil {
		_ = os.Remove(tmpPath) // F5724: don't strand a partial body in tmp/
		return "", fmt.Errorf("failed to write message: %w", err)
	}

	// Sync to disk for durability
	if err := syncFile(tmpPath); err != nil {
		_ = os.Remove(tmpPath)
		return "", fmt.Errorf("failed to sync temp file: %w", err)
	}

	// Atomic rename to new/
	if err := os.Rename(tmpPath, newPath); err != nil {
		_ = os.Remove(tmpPath)
		return "", fmt.Errorf("failed to move message to new/: %w", err)
	}

	// Best-effort sync of new/ directory to ensure rename durability
	s.syncDir(filepath.Join(basePath, "new"))

	return uniqueName, nil
}

// DeliverWithFlags stores a message directly to cur/ with specified flags
func (s *MaildirStore) DeliverWithFlags(domain, user, folder string, msg []byte, flags string) (string, error) {
	if err := s.ensureFolder(domain, user, folder); err != nil {
		return "", err
	}

	basePath := s.folderPath(domain, user, folder)
	uniqueName := s.generateUniqueName()

	// Add flags to filename using platform separator
	uniqueName = joinFlags(uniqueName, flags)
	if err := validateFilename(uniqueName); err != nil {
		return "", err
	}

	// Write to tmp directory first
	tmpPath := filepath.Join(basePath, "tmp", uniqueName)
	curPath := filepath.Join(basePath, "cur", uniqueName)

	// Write file
	if err := os.WriteFile(tmpPath, msg, 0o600); err != nil {
		_ = os.Remove(tmpPath) // F5724: don't strand a partial body in tmp/
		return "", fmt.Errorf("failed to write message: %w", err)
	}

	// Sync to disk for durability
	if err := syncFile(tmpPath); err != nil {
		_ = os.Remove(tmpPath)
		return "", fmt.Errorf("failed to sync temp file: %w", err)
	}

	// Atomic rename to cur/
	if err := os.Rename(tmpPath, curPath); err != nil {
		_ = os.Remove(tmpPath)
		return "", fmt.Errorf("failed to move message to cur/: %w", err)
	}

	// Best-effort sync of cur/ directory to ensure rename durability
	s.syncDir(filepath.Join(basePath, "cur"))

	return uniqueName, nil
}

// Fetch reads a message by its filename
func (s *MaildirStore) Fetch(domain, user, folder, filename string) ([]byte, error) {
	if err := validateFilename(filename); err != nil {
		return nil, err
	}
	basePath := s.folderPath(domain, user, folder)
	if basePath == "" {
		return nil, fmt.Errorf("invalid mailbox path")
	}

	// Try cur/ first, then new/
	paths := []string{
		filepath.Join(basePath, "cur", filename),
		filepath.Join(basePath, "new", filename),
	}

	for _, path := range paths {
		data, err := os.ReadFile(filepath.Clean(path))
		if err == nil {
			return data, nil
		}
		if !os.IsNotExist(err) {
			return nil, fmt.Errorf("failed to read message: %w", err)
		}
	}

	return nil, fmt.Errorf("message not found: %s", filename)
}

// FetchReader returns a reader for a message
func (s *MaildirStore) FetchReader(domain, user, folder, filename string) (io.ReadCloser, error) {
	if err := validateFilename(filename); err != nil {
		return nil, err
	}
	basePath := s.folderPath(domain, user, folder)
	if basePath == "" {
		return nil, fmt.Errorf("invalid mailbox path")
	}

	// Try cur/ first, then new/
	paths := []string{
		filepath.Join(basePath, "cur", filename),
		filepath.Join(basePath, "new", filename),
	}

	for _, path := range paths {
		file, err := os.Open(filepath.Clean(path))
		if err == nil {
			return file, nil
		}
		if !os.IsNotExist(err) {
			return nil, fmt.Errorf("failed to open message: %w", err)
		}
	}

	return nil, fmt.Errorf("message not found: %s", filename)
}

// syncDir performs a best-effort fsync on a directory for durability.
// On Windows this may fail silently, which is acceptable.
func (s *MaildirStore) syncDir(dir string) {
	f, err := os.Open(filepath.Clean(dir))
	if err != nil {
		return
	}
	_ = f.Sync()  // Best-effort, best-effort sync failures are acceptable
	_ = f.Close() // Best-effort close failures are acceptable
}

// syncFile opens a file with read-write access, syncs it to disk, and closes it.
// Using a dedicated function ensures the file descriptor is released
// before any rename operation (required on Windows).
func syncFile(path string) error {
	f, err := os.OpenFile(filepath.Clean(path), os.O_RDWR, 0)
	if err != nil {
		return err
	}
	defer f.Close()
	return f.Sync()
}

// Move moves a message from one folder to another
func (s *MaildirStore) Move(domain, user, fromFolder, toFolder, filename string) error {
	if err := validateFilename(filename); err != nil {
		return err
	}
	// Ensure destination folder exists
	if err := s.ensureFolder(domain, user, toFolder); err != nil {
		return err
	}

	fromBase := s.folderPath(domain, user, fromFolder)
	toBase := s.folderPath(domain, user, toFolder)
	if fromBase == "" || toBase == "" {
		return fmt.Errorf("invalid mailbox path")
	}

	// Find source file (strip any flags using platform separator)
	baseName, _ := splitFlags(filename)

	// Try moving directly without Stat checks to avoid TOCTOU race.
	// Construct candidate paths and attempt Rename; if none succeed, report failure.
	var fromPath string
	candidates := []string{
		filepath.Join(fromBase, "cur", filename),
		filepath.Join(fromBase, "cur", baseName),
		filepath.Join(fromBase, "new", filename),
		filepath.Join(fromBase, "new", baseName),
	}

	// Generate new unique name for destination to avoid collisions
	uniqueName := s.generateUniqueName()
	for _, path := range candidates {
		_, flags := splitFlags(filepath.Base(path))
		toPath := filepath.Join(toBase, "new", joinFlags(uniqueName, flags))
		if err := os.Rename(path, toPath); err == nil {
			fromPath = path
			break
		}
	}

	if fromPath == "" {
		return fmt.Errorf("source message not found: %s", filename)
	}

	// Best-effort sync of destination new/ directory
	s.syncDir(filepath.Join(toBase, "new"))

	return nil
}

// SetFlags updates the flags on a message (moves between cur/ filenames)
func (s *MaildirStore) SetFlags(domain, user, folder, filename string, flags string) error {
	if err := validateFilename(filename); err != nil {
		return err
	}
	basePath := s.folderPath(domain, user, folder)
	if basePath == "" {
		return fmt.Errorf("invalid mailbox path")
	}

	// Extract base name (without flags)
	baseName, _ := splitFlags(filename)

	// Build new filename with flags
	newName := joinFlags(baseName, flags)
	if err := validateFilename(newName); err != nil {
		return err
	}

	// Try renaming directly without Stat checks to avoid TOCTOU race.
	// Construct candidate paths in cur/ and new/ and attempt Rename.
	newPath := filepath.Join(basePath, "cur", newName)
	var oldPath string
	for _, sd := range []string{"cur", "new"} {
		candidate := filepath.Join(basePath, sd, filename)
		if err := os.Rename(candidate, newPath); err == nil {
			oldPath = candidate
			break
		}
	}

	if oldPath == "" {
		return fmt.Errorf("message not found: %s", filename)
	}

	// If the source was in new/, ensure cur/ exists (best-effort, already created by Rename if needed on most filesystems)
	_ = os.MkdirAll(filepath.Join(basePath, "cur"), 0o750)

	// Best-effort sync of cur/ directory
	s.syncDir(filepath.Join(basePath, "cur"))

	return nil
}

// List returns all messages in a folder
func (s *MaildirStore) List(domain, user, folder string) ([]MessageInfo, error) {
	basePath := s.folderPath(domain, user, folder)
	if basePath == "" {
		return nil, fmt.Errorf("invalid mailbox path")
	}

	var messages []MessageInfo

	// List files from both new/ and cur/
	subdirs := []string{"new", "cur"}

	for _, subdir := range subdirs {
		dirPath := filepath.Join(basePath, subdir)
		entries, err := os.ReadDir(dirPath)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("failed to read directory %s: %w", dirPath, err)
		}

		for _, entry := range entries {
			if entry.IsDir() {
				continue
			}

			info, err := entry.Info()
			if err != nil {
				continue
			}

			filename := entry.Name()

			// Extract flags from filename using platform separator
			_, flags := splitFlags(filename)

			messages = append(messages, MessageInfo{
				Filename: filename,
				Size:     info.Size(),
				ModTime:  info.ModTime(),
				Flags:    flags,
			})
		}
	}

	return messages, nil
}

// Delete removes a message permanently
func (s *MaildirStore) Delete(domain, user, folder, filename string) error {
	if err := validateFilename(filename); err != nil {
		return err
	}
	basePath := s.folderPath(domain, user, folder)
	if basePath == "" {
		return fmt.Errorf("invalid mailbox path")
	}

	// Try to find and delete from cur/ or new/
	for _, subdir := range []string{"cur", "new"} {
		path := filepath.Join(basePath, subdir, filename)
		if err := os.Remove(path); err == nil {
			return nil
		}
	}

	return fmt.Errorf("message not found: %s", filename)
}

// CreateFolder creates a new folder
func (s *MaildirStore) CreateFolder(domain, user, folder string) error {
	return s.ensureFolder(domain, user, folder)
}

// DeleteFolder removes a folder and all its messages
func (s *MaildirStore) DeleteFolder(domain, user, folder string) error {
	if folder == "INBOX" || folder == "" {
		return fmt.Errorf("cannot delete INBOX folder")
	}

	basePath := s.folderPath(domain, user, folder)
	if basePath == "" {
		return fmt.Errorf("invalid mailbox path")
	}
	if err := os.RemoveAll(basePath); err != nil {
		return fmt.Errorf("failed to delete folder: %w", err)
	}

	return nil
}

// RenameFolder renames a folder
func (s *MaildirStore) RenameFolder(domain, user, oldName, newName string) error {
	if oldName == "INBOX" || oldName == "" {
		return fmt.Errorf("cannot rename INBOX folder")
	}

	oldPath := s.folderPath(domain, user, oldName)
	newPath := s.folderPath(domain, user, newName)
	if oldPath == "" || newPath == "" {
		return fmt.Errorf("invalid mailbox path")
	}

	if err := os.Rename(oldPath, newPath); err != nil {
		return fmt.Errorf("failed to rename folder: %w", err)
	}

	return nil
}

// ListFolders returns all folders for a user
func (s *MaildirStore) ListFolders(domain, user string) ([]string, error) {
	maildir, err := s.userMaildirPath(domain, user)
	if err != nil {
		return nil, err
	}

	var folders []string

	// Always include INBOX (the main Maildir)
	folders = append(folders, "INBOX")

	// List subdirectories starting with "."
	entries, err := os.ReadDir(maildir)
	if err != nil {
		if os.IsNotExist(err) {
			return folders, nil
		}
		return nil, fmt.Errorf("failed to read maildir: %w", err)
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		name := entry.Name()
		if strings.HasPrefix(name, ".") {
			// Remove leading dot for folder name
			folder := name[1:]
			folders = append(folders, folder)
		}
	}

	return folders, nil
}

// Quota returns current usage and limit for a user
func (s *MaildirStore) Quota(domain, user string) (used int64, limit int64, err error) {
	maildir, err := s.userMaildirPath(domain, user)
	if err != nil {
		return 0, 0, err
	}

	// Walk the directory tree and sum file sizes
	err = filepath.Walk(maildir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			if os.IsNotExist(err) {
				return nil
			}
			return err
		}
		if !info.IsDir() {
			used += info.Size()
		}
		return nil
	})

	if err != nil && !os.IsNotExist(err) {
		return 0, 0, fmt.Errorf("failed to calculate quota: %w", err)
	}

	return used, 0, nil // Limit is managed elsewhere (in domain config)
}

// MessageCount returns the number of messages in a folder
func (s *MaildirStore) MessageCount(domain, user, folder string) (int, error) {
	messages, err := s.List(domain, user, folder)
	if err != nil {
		return 0, err
	}
	return len(messages), nil
}
